### PR TITLE
Quantum tomography

### PR DESCRIPTION
**Pull request by PrinceOfPuppers**
Hyperparameter change can be ignored, i removed a comment when taking a screenshot for the slides

beyond that everything should be in order

### CODE REVIEW

**Comment by nmdickso** [comment]
I'm just gonna change the hyperparameters back, move it all into the example folder and get rid of the empty files (??) and then we should be good

**Comment by nmdickso** [comment]
Theres also some pep-8 stuff to fix (like an almost hilarious amount of it 
image my linter is _shitting_ itself,

but I'll fix those when I do documentation, it's 99% spacing.

**Comment by PrinceOfPuppers** [comment]
added the file creation and such. closed and reopened pull request so the changes should hopefully be in it if that is how it works.

**Review by nmdickso — APPROVED** [review]
> added the file creation and such. closed and reopened pull request so the changes should hopefully be in it if that is how it works.

Just FYI you don't have to close and reopen, any new commits are automatically added to the PR.
But yeah, looks good enough to merge to me now.

**Pull request merged**
